# Generated by Django 3.2.12 on 2022-03-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='frequency',
        ),
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
